---
log:
  path: "train_log"
  stamped: True

data_loader_params:
  batch_size: 128
  shuffle: True
  num_workers: 8

dataset_params:
  samples: 1000 # the number of files to use for the learning. If not set, all the files in the dir are used.
  steps: 15
  dir: "data/csv/sub/"
  split: 0.7 # 70% for learning, 30% for validation.
  v_frame: "world" # The frame in which the velocity is expressed.
  dv_frame: "world" # The frame in which the velocity delta is expressed.
  act_normed: True

model:
  rnn:
    rnn_layer: 5
    rnn_hidden_size : 1
    bias: True
    activation: "tanh" # rnn supports 'relu' and 'tanh' (default)
  fc:
    topology: [32, 32]
    activation: "LeakyRelu"
    bias: True
    batch_norm: True

optim:
  type: "Adam"
  lr: 1.e-4
  epochs: 2
