data_loader_params:
  batch_size: 512
  num_workers: 8
  shuffle: true
dataset_params:
  act_normed: true
  dir: ../data/csv/tests/
  dv_frame: world
  out_normed: false
  samples: 10
  split: 0.7
  steps: 15
  v_frame: world
log:
  path: train_log
  stamped: true
loss:
  dv: 1.0
  traj: 1.0
  type: traj
  vel: 1.0
model:
  fc:
    activation: LeakyRelu
    batch_norm: true
    bias: true
    relu_neg_slope: 0.1
    topology:
    - 128
    - 128
  rnn:
    activation: tanh
    bias: true
    rnn_hidden_size: 64
    rnn_layer: 1
  se3: true
optim:
  epochs: 4
  lr: 0.0001
  type: Adam
